# Generated by Django 2.2.28 on 2024-11-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='etat_prerequis',
            field=models.CharField(default='moche', max_length=200),
            preserve_default=False,
        ),
    ]
