# Generated by Django 2.2.28 on 2024-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_equipement_etat_prerequis'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='etat_suivant',
            field=models.CharField(default='moche', max_length=200),
            preserve_default=False,
        ),
    ]
